build:
    except:
        - master
    tags:
        - docker-image-build
    script: ""
    variables:
        TO: ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}
        
build-latest:
    only:
        - master
    tags:
        - docker-image-build
    script: ""
    variables:
        TO: ${CI_REGISTRY_IMAGE}:latest
        