image: docker:latest

stages:
    - build
    - release

before_script:
    - docker login -p "${REGISTRY_PASSWD}" -u "${REGISTRY_USER}" "${CI_REGISTRY}"

after_script:
    - docker logout "${CI_REGISTRY}"

build-image:
    stage: build
    script:
        - docker build --pull --no-cache=true --rm=true -t "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}" .
        - docker push "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}"

release-image:
    stage: release
    only:
        - master
    script:
        - docker tag "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}" "${CI_REGISTRY_IMAGE}:latest"
        - docker push "${CI_REGISTRY_IMAGE}:latest"

